USE [HladnjacaDB]
GO

/****** Object:  Index [NonClusteredIndex-20210602-184751]    Script Date: 6/2/2021 10:45:38 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210602-184751] ON [dbo].[Klijents]
(
	[Id] ASC,
	[Jmbg] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


