//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizacionaJedinica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizacionaJedinica()
        {
            this.Hladnjacas = new HashSet<Hladnjaca>();
            this.Podredjena = new HashSet<OrganizacionaJedinica>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> OrganizacionaJedinicaId_nadredjena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hladnjaca> Hladnjacas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizacionaJedinica> Podredjena { get; set; }
        public virtual OrganizacionaJedinica Nadredjena { get; set; }
    }
}
