//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otkupljuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otkupljuje()
        {
            this.PrenosiSes = new HashSet<PrenosiSe>();
        }
    
        public int PoljoprivredniTehnicarMbr { get; set; }
        public int VoceId { get; set; }
        public int KartonId { get; set; }
        public int KartonUgovorId { get; set; }
        public int KartonUgovorKlijentId { get; set; }
        public int KartonUgovorHladnjacaId { get; set; }
    
        public virtual PoljoprivredniTehnicar PoljoprivredniTehnicar { get; set; }
        public virtual Voce Voce { get; set; }
        public virtual Karton Karton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrenosiSe> PrenosiSes { get; set; }
    }
}
