//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrenosiSe
    {
        public int TransportId { get; set; }
        public int OtkupljujePoljoprivredniTehnicarMbr { get; set; }
        public int OtkupljujeVoceId { get; set; }
    
        public virtual Transport Transport { get; set; }
        public virtual Otkupljuje Otkupljuje { get; set; }
    }
}
