//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ugovor()
        {
            this.Kartons = new HashSet<Karton>();
        }
    
        public int Id { get; set; }
        public string Tip { get; set; }
        public System.DateTime DatumPotpisivanja { get; set; }
        public int KlijentId { get; set; }
        public int HladnjacaId { get; set; }
    
        public virtual Klijent Klijent { get; set; }
        public virtual Hladnjaca Hladnjaca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karton> Kartons { get; set; }
    }
}
