//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        public int Mbr { get; set; }
        public int Jmbg { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Kategorija { get; set; }
        public int HladnjacaId { get; set; }
    
        public virtual Hladnjaca Hladnjaca { get; set; }
    }
}
